### PR TITLE
HAL

### PR DESCRIPTION
**Pull request by dmcnaugh**
HAL devices differ slightly to the ESP32 port as we are not dealing with the same devices (ie. no UARTs)

Default device assignments (ie same configuration as before introducing HAL)  are:
- SIO1.portA.device=WEBTTY,STDIO
- SIO1.portB.device=VIOKBD
- SIO2.portA.device=SCKTSRV
- SIO2.portB.device=MODEM

This should go some why to explaining what the devices are named.

I have also added virtual baud rate code to SIO1B
- the use case here is for someone that doesn't want to use the VIO but wants more devices available

I have tested everything except the socket server SCKTSRV (on SIO2A by default) because I am unsure of the setup required.

Future expansion of the devices available through the HAL could include:
- multiple socket servers (like for cpmsim)
- multiple modems
- physical serial ports (eg. /dev/tty.usb... or /dev/ttyS0, etc...)
- multiple TTY: type devices on the webUI

Each of the "multiple" device ideas could benefit from changing the underlying device code to C++  to make it simpler to manage multiple instances based on a common class.

Looking over the code again as I worked to integrate it here makes me realise there could be many improvements made:
- the main open question for me is: should handling of "last" be a function of the SIO code or moved into the HAL code
- but please go ahead and make any improvements you see fit

PS. I have only updated **GNUmakefile** and leave it to you to add the new files for the HAL code to the platform specific makefiles.

Cheers,
Dave.

### CODE REVIEW

**Comment by udo-munk** [comment]
First of all, in 1.37 there was a bug in porta.sub on the CPM 2.2 disk, seems I changed
the label name for tty2 out but forgot to change it in the submit script as well. This is
corrected.

To test the socketserver use either minicom or BSD netcat (GNU netcat won't work) as
follows:

First start the IMSAI emulation.
Then connect to the UNIX socket with minicom:
minicom -D unix#/tmp/.z80pack/imsaisim.sio2a
or with netcat:
/usr/bin/nc -U /tmp/.z80pack/imsaisim.sio2a

Then run (the corrected) porta.sub to patch for using SIO 2A.
After that you can
pip pun:=boot.asm
to dump something to the socketserver or
pip con:=uc1:
to switch the console to it.

Doesn't work anymore after merging the HAL, socketserver seems to be broken.

**Comment by udo-munk** [comment]
The handling of last depends on the UART or SIO chip used on the serial card. If you
move it into the HAL it also needs to know which kind of chip is emulated, in case
someone implements some other that behaves different.

For the Altair SIO some tricky boot code exists that depends on this, don't know how the
other UART chips behave. The LSI UART's usually use a shift register separate from the
parallel register and copy contents after a complete frame without parity error was
received. On other serial cards you can read the shift register directly and watch
the serial bits geting shifted in.

**Comment by udo-munk** [comment]
The socket server HAL has a logical design problem:
Initialy the alive status is not set, because the socket is not connected.
New connections are accepted in the status routine, but the status routine never gets called because the connection is not alive.

**Comment by udo-munk** [comment]
If I modify scktsrv_alive() to return always 1 I can do I/O on the UNIX socket again.

**Comment by dmcnaugh** [comment]
> The handling of last depends on the UART or SIO chip used on the serial card.

So the handling of `last` belongs in the SIO code where it is now, and I am happy to leave it there.

> If I modify scktsrv_alive() to return always 1 I can do I/O on the UNIX socket again.

This is the simple solution that restores functionality to pre-HAL behaviour.
But there is another design consideration and alternative:
- the purpose for `device_alive()` it to allow unconnected devices to fall-through to the next device
  - if `device_alive()` always returns 1, the device is always connected and "owns" the SIO port
  - if `device_alive()` is conditional on the connection state of a device eg. a websocket or a socket, then if a device is not connected it will *yield* the SIO port to the next device on the device list

For example: if you set
`SIO1.portA.device=SCKTSRV,WEBTTY,STDIO`

If you have **minicom** connected to the socket, then it is the console; if not, but if TTY: on the WebUI is connected then it is the console; if not then STDIO will be the console as it is always "alive" (=1)

This is easily done by moving the code that checks for a socket connection from `scktsrv_status()` to `scktsrv_alive()`

I will post another PR with this change, along with a few other issues that I have picked up.

**Pull request merged**
