### PR TITLE
Intel MDS work

### PR DESCRIPTION
**Pull request by sneakywumpus**
Use original CP/M boot.asm from CP/M OEM [disk](http://www.cpm.z80.de/download/cpm22red.zip).

Fix putsys to actually allow to use all 52 sectors.

Add support for the iSBC-206 controller to the CP/M BIOS.
The cpm.bin file was build by hand, since I couldn't get movcpm to work (it hangs when trying to build
a 62k system).

Add ISIS system and user hard disk images.

### CODE REVIEW

**Comment by sneakywumpus** [comment]
Please tell me, if the BIOS disk definition parameters for the hard disk make sense.

**Comment by udo-munk** [comment]
What exactly is your problem with movcpm? This looks ok:

62K CP/M VERS 2.2

A>movcpm 62 *

CONSTRUCTING 62k CP/M vers 2.2
READY FOR "SYSGEN" OR
"SAVE 35 CPM62.COM"
A>save 35 cpm62.sys
A>stat cpm62.sys

 Recs  Bytes  Ext Acc
   70    10k    1 R/W A:CPM62.SYS
Bytes Remaining On A: 338k

**Comment by udo-munk** [comment]
This doesn't work, serial number not matching:

A>ddt movcpm.com
DDT VERS 2.2
NEXT  PC
2800 0100
-i64 *
-g

CONSTRUCTING 64k CP/M vers 2.2
SYNCRONIZATION ERROR

**Comment by sneakywumpus** [comment]
I'm the guy who sits in front of the controls of a nuclear power plant and says "Let's just hit some buttons and see what happens... Ooops, perhaps I should have read the manual".

I now studying the CP/M manual, especially "Section 6 - CP/M 2 Alteration".

Sorry for the noise.

**Comment by udo-munk** [comment]
No problem, without reading the alteration guilde it will be difficult ;-)

**Comment by sneakywumpus** [comment]
I can't get this to work. If I use "movcpm 62 *" the CCP begins at 0DC00H, but the CP/M that Intel delivered in the boot tracks begins at 0DA00H and I wan't one that begins at 0DB00H, since I reduced the size of the BIOS.

**Comment by udo-munk** [comment]
This is not possible with movcpm because you can tell memory size only in kilobytes, but not in pages. For relocating to some specific memory page one needs to assemble CCP, BDOS and BIOS with the wanted origin, and put an image of this into memory @ 0980H for sysgen.

**Comment by sneakywumpus** [comment]
Nothing is impossible. Found a knob by looking at the source code of movcpm.

The byte at address 023d defines the BIOS workspace (i.e. RAM after the BIOS code) in pages that is added to the module size. By changing that, one can move CP/M in page increments.

**Pull request merged**
