### PR TITLE
try to get the imsai-fif hd disk to get along with the disk manager

### PR DESCRIPTION
**Pull request by sneakywumpus**
I tried to name the disk "hd0.hdd" to make it show up as a hard disk drive in the web frontend, but that
didn't work. Maybe the web code needs to be changed?

### CODE REVIEW

**Comment by udo-munk** [comment]
That is the name for the disk Dave uses in the ESP32 machines. Here it always was named drivei.dsk, maybe that works. I don't know anymore, I remember we had great difficulties to make this work on z80pack and the ESP32 IMSAI. Also Dave said we can always get new web content from the ESP32 repo and try it out, should be compatible and it is a while since I updated it the last time.

**Comment by sneakywumpus** [comment]
Where is the ESP32 repo?

**Comment by udo-munk** [comment]
The HD works with disks/drivei.dsk and also shows in the webfrontend :)

https://github.com/thehighnibble

**Comment by udo-munk** [comment]
the drive I; comes from cpmsim, we can rename it here, no problem.

**Comment by udo-munk** [comment]
Not the drive letter, the filename for the disk image I meant.

**Comment by udo-munk** [comment]
Dave used the extension .hdd for harddisks, so that the diskmanager won't get confused, is only looking for .dsk images.

**Comment by sneakywumpus** [comment]
It says in big fat letters "THESE PACKAGES MAY NOT BE UPLOADED OR HOSTED ANYWHERE ELSE." on the web page.
Is it alright, if I update the web code from the latest release?

**Comment by udo-munk** [comment]
Yes sure, we have Daves's permission for this. You need only the www contents and copy it over to ours, everything identical in the ESP32 machines and here. And if the webfrontends still look ok and work just commit all the changes in www.

**Comment by sneakywumpus** [comment]
Hmm, doesn't work at all, probably needs updated versions of netsrv.[ch].
Even tried updating civetweb to the latest release.

**Comment by udo-munk** [comment]
OK, not compatible anymore, nothing we can do about this.

**Comment by sneakywumpus** [comment]
Ahem... stupid me, just needed to clear the browser cache...

**Comment by udo-munk** [comment]
Ahhh, OK, that is very essential for the web frontends, most browser caches are to dumb to handle this correct.

**Pull request merged**
