### PR TITLE
update no-OS-FatFS-SD-SDIO-SPI-RPi-Pico RISC-V code; reduce source code duplication

### PR DESCRIPTION
**Pull request by sneakywumpus**
Changes to not disturb the ARM side of things.

### CODE REVIEW

**Comment by udo-munk** [comment]
I thought I update to the latest FatFS version now everywhere where it is included. Then this won't be necessary?

**Comment by sneakywumpus** [comment]
It's currently only in the dev branch.

**Comment by sneakywumpus** [comment]
Arghh.. Sorry just pushed a bunch of other stuff intended for the next pull request...

**Comment by udo-munk** [comment]
No problem, this is better anyway. I tried to move the libs to some common lib dir before, but failed with that cmake stuff ;-)

**Comment by udo-munk** [comment]
Yep, works.

Please don't. There are many many people who just like to use the GEEK CP/M machine, but are not able to setup the SDK and compile it them self. That is why I added a directory with the latest build, so that they just have to flash it. I also would like to create another repo for the RP2350-GEEK when the devices arrive, to make it as easy as possible for those who just want to use it. The z80pack repo is complex enough already.

**Comment by sneakywumpus** [comment]
Ok.

**Pull request merged**
