### PR TITLE
use C standard integer types

### PR DESCRIPTION
**Pull request by sneakywumpus**
Declare BYTE, WORD, and SWORD exactly.
Use uint64_t for clock values.

The designated initializer syntax was actually GNU C, make it standard by adding " = ".

Use standard uint<n>_t types in the frontpanel library.

Use off_t for seek offsets.

### CODE REVIEW

**Comment by udo-munk** [comment]
ARM compiler doesn't like this:

[ 19%] Building C object CMakeFiles/picosim.dir/picosim.c.obj
[ 20%] Building C object CMakeFiles/picosim.dir/home/udo/work/z80pack/z80core/simcore.c.obj
/home/udo/work/z80pack/z80core/simcore.c: In function 'report_cpu_stats':
/home/udo/work/z80pack/z80core/simcore.c:291:21: error: expected ')' before 'PRIu64'
  291 |   printf("CPU ran %" PRIu64 " ms ", cpu_time / 1000);
      |                     ^~~~~~~
      |                     )
/home/udo/work/z80pack/z80core/simcore.c:292:26: error: expected ')' before 'PRIu64'
  292 |   printf("and executed %" PRIu64 " t-states\n", T);
      |                          ^~~~~~~
      |                          )

**Comment by sneakywumpus** [comment]
What ARM toolchain do you use? Here on Arch Linux, picosim compiles fine.

**Comment by udo-munk** [comment]
gcc-arm-none-eabi/jammy,now 15:10.3-2021.07-4 amd64 [installed]
  GCC cross compiler for ARM Cortex-R/M processors

**Comment by udo-munk** [comment]
On OSX the ARM compiler also has no problem. On Ubuntu Linux I checked, no update available is latest version installed.

**Comment by sneakywumpus** [comment]
Bummer. The newlib library delivered by Ubuntu doesn't have _WANT_IO_C99_FORMATS enabled...

**Pull request merged**
