### PR TITLE
Implementation of full undocumented z80 opcodes

### PR DESCRIPTION
**Pull request by chastai**
Hello,

I've followed the information in the z80-undocumented pdf.

I've reviewed the code, it is quite easy as there are no much changes but it would be nice to test it with programs requiring undoc instructions.

In the document, it is mentioned that the ED 4E and ED 6E opcodes behave like IM 0 with an exception when a particular value is put on the bus. I've implemented these instructions like IM 0 without the exception as I was not sure how to do it.

For instructions trapped because of the -u option, the unwanted instruction was still executed, I've removed this behaviour or maybe there was a reason for that?

Also, normally, when ED is followed by an unknow opcode, the two bytes should be interpreted as two NOPs but in the current implementation, a trap is executed.
and DD or FD followed by an unknow opcode shouldn't trigger a trap either.
This is still to fix.

There is still to implement the undocumented instructions for the disassembler.

### CODE REVIEW

**Comment by udo-munk** [comment]
Sorry, I won't accept macros generating the op-code functions, for every op-code we want just a function which does the boolean logic in a readable manner. I also have resisted to use macros, because the code is written once, but read many many times.

Currently all undocumented instructions are implemented that were used on such machines by some early Z80 developers with close contacts to Zilog. I'm not aware about any early software not running because of missing instructions with 1.36. Most of the 700+ instructions are useless, were never used and will never be used, it is just dead code in the binary blowing up the code size. Also the software is used on systems without demand paging, where unneeded code really hurts. This also is why the undocumented instructions are conditional compiled, so that the code size will be smaller if the instructions aren't used anyway.

I knew that ca. 2 dozends of the instructions are needed to run some of the vinatge software, so I just used the #ifdef in the op-code tables. This of course would be more readable by using a macro, that either compiles the trap or the undocumented instruction, so this can be implemented like you did.

Of course a real Z80 has no traps and will execute any nonsense endless. The reason for early traps in the emulation are for tracing back to the point, where things obvisouly go wrong, because no one would use a prefix followed by something executed as NOP. That likely is not code intended for execution, but some data area. You really should think about it, if you really need to excute bogus instruction sequences, that never ever were programmed intentionally.

**Comment by chastai** [comment]
Hello,

I think that "wrong" opcodes or combinations of prefix/opcode should be trapped --only-- with the -u flag.

I do not understand your favour for copy/pasting but to everyone his thing ;-)

I would be happy to help anyone who has a issue with my implementation.

**Comment by EtchedPixels** [comment]
A lot of code uses the half-IX and half-Y instructions as well as the magic shifts so I want to run without -u, but I also want to see traps if I go randomly off into nonsense code.

I guess you'd need need a -u and -U or something ?

**Comment by chastai** [comment]
Indeed, it would be better to distinguish undocumented opcodes from unknown opcodes.
I suggested that to make the emulator more accurate and why not to give a chance to the poor program that has gone wild to fall back on its feet but for debugging, the current behaviour is fine.

Note that my patches don't change the current behaviour, so unknown opcodes are always trapped.

**Comment by udo-munk** [comment]
There are no wrong op-codes, the original CPU's will execute anything as long as they got power and clock cycles. There are unimplemented instructions and these will trap of course. Then there are undocumented instructions, which can conditionally be compiled in or not, if compiled in they should trap with -u for easier debugging. If not compiled in they are unimplemented and trap of course. For the Z80 I tried to balance between unneeded code overhead and debugging aids, so this might look a bit odd at first, it is not really consistent. The 8080 is much easier because it only has 12 undocumented instructions, so the implementation is consistent and works like what you also want for the Z80. For making it consistent all undocumented instructions need to be implemented, but that has disadvantages, like 2/3 of the code never used and mostly untested.
The instruction exercisers help some with this, but I found more bugs by other means as with these programs, they test only a fraction of the instruction set.

Maybe one should implement something like -u[123...] which defines groups of undocumented instructions then, which will trap, while the others still are executed. Quite some work, but probaly a good solution and it would do what was intended.

I do not have a favour for copa&paste, but decades ago I made some design decisions, which turned out to be good. No functions generated by macros, not more precalculated tables other than for the CRC, so every average C programmer can look into some op-code function, see what it does and maybe improve/fix it, without the need to read and understand a layer of macros or some magic numbers in tables. The copy&paste is a result of this unfortunately, but I don't mind because you do it only once, while many are reading the sources again and again. Main focus has to be on readable and understandable source code, not minimalizing work writing it and obfuscate something more than required for a correct working implementation.

I don't opt against implementation of all op-codes and execution of meaningless prefixes, as long as this can be compiled conditionally, and if it is compiled in the possibility to trap for debugging. And please implement functions without macros, thanks. Using macros instead of the #ifdefs in the op-code tables is fine, that is a usage that actually would improve readability.

**Comment by chastai** [comment]
It's why I've put wrong in quotation marks.
Our points of view are divergent, there is no need to get into a stew. It's also why forks exist.
Rendez-vous at chastai/z80pack, branch z80-undoc for the interested.

**Comment by udo-munk** [comment]
No problem, I just tried to explain why I don't want to merge this pull request.

**Pull request closed without merging**
