### PR TITLE
sync with RP2040-GEEK-80

### PR DESCRIPTION
**Pull request by sneakywumpus**
Please test, can't do this myself.

### CODE REVIEW

**Comment by udo-munk** [comment]
Everything works but the USB mass storage device on Windows. The drive becomes visible after a while, but doesn't contain a media with filesystem.

**Comment by udo-munk** [comment]
Also not working with OSX, no Volume gets mounted.

**Comment by udo-munk** [comment]
Tested with the GEEK on OSX. The Volume immeditaly shows up and can be browsed. Ejecting the drive removes it, but picosim won't notice and is still waitig for the drive to be ejected.

**Comment by sneakywumpus** [comment]
Hmm. Switched the GEEK from SDIO to SPI. USB mass storage doesn't work anymore, can't even eject, config menu can still list files.

**Comment by udo-munk** [comment]
SPI on the GEEK works fine, I tested that for a while bevore moving to SDIO. It is slower, but not that much when accessing disk images. The files are too small to even notice the difference.

**Pull request merged**
